// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: employees.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createEmployee = `-- name: CreateEmployee :execresult
INSERT INTO employees 
(id, created_at, updated_at, emp_role, emp_name, department) 
VALUES (?,?,?,?,?,?)
`

type CreateEmployeeParams struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	EmpRole    string
	EmpName    string
	Department string
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEmployee,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.EmpRole,
		arg.EmpName,
		arg.Department,
	)
}
