// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type Employee struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	EmpName    string
	Department string
	EmpRole    string
}
